name: CI

on:
  push:
    branches: [ main, prod ]
  pull_request:
    branches: [ main, prod ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install uv
        uv venv
        source .venv/bin/activate
        uv pip install ".[dev,test]"
    
    - name: Lint with flake8
      run: |
        source .venv/bin/activate
        flake8 src/ --count --show-source --statistics
    
    - name: Run tests
      run: |
        source .venv/bin/activate
        pytest

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1 libglib2.0-0
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install uv
        uv venv
        source .venv/bin/activate
        uv pip install .
    
    - name: Verify import
      run: |
        source .venv/bin/activate
        python -c "import streamlit; import cv2; import numpy" 